In [ ]:
import numpy as np

In [ ]:
identidad = np.eye(4)

In [ ]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
vector = np.array([[2],[3],[5],[7]])

In [ ]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [ ]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [ ]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

In [ ]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [ ]:
inversa_A = np.linalg.inv(A)

In [ ]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [ ]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
singular = np.array([[1,1],[1,1]])

In [ ]:
print(singular)

[[1 1]
 [1 1]]


In [ ]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8c997035-8f7f-462c-b500-b118b8333440' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>